### ISSUE TITLE
Editor de código

### ISSUE THREAD

**Issue by GeandreRibeiro** [Leeaandrob/challenge-alpha#1]
Qual o melhor editor de código python qual é o mais usado?

**Comment by hengling** [comment]
Oi @GeandreRibeiro, eu baixei o PyCharm da JetBrains e estou gostando muito!
Se vc já utiliza o IntelliJ ou WebStorm vai se sentir em casa, pois é bem parecido.
Se preferir algo mais leve, eu aconselho a utilizar o Brackets ou Sublime.

Espero ter ajudado!

Abraços!

**Comment by GeandreRibeiro** [comment]
valew pela resposta eu estou usando o PyCharm também e estou gostando... acho que vou ficar com ele mesmo.

**Comment by Leeaandrob** [comment]
eu uso o vim somente galera.
